# Generated by Django 6.0.5 on 2026-06-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('clinician', 'Clinician')], default='patient', max_length=10),
        ),
    ]
