# Generated by Django 6.0.5 on 2026-06-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_myuser_is_verified_clinician_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_verified_clinician',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='verification_requested',
        ),
    ]
