# Generated by Django 6.0.5 on 2026-06-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_myuser_is_verified_clinician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_verified_clinician',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='verification_requested',
            field=models.BooleanField(default=False),
        ),
    ]
