# Generated by Django 6.0.5 on 2026-06-01 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='symptom_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='symptoms.symptomreport'),
        ),
    ]
