# Generated by Django 6.0.5 on 2026-06-01 11:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chemotherapy', '0001_initial'),
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemotherapy_cycle_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptom_reports', to='chemotherapy.chemotherapycycle')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'symptoms reports',
            },
        ),
        migrations.CreateModel(
            name='SymptomsEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('clinical_grade', models.IntegerField(choices=[(0, 'None'), (1, 'Mild'), (2, 'Moderate'), (3, 'Severe'), (4, 'Very Severe')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptom_entry', to='patients.patient')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptom_entry', to='core.symptoms')),
                ('symptom_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptom_entry', to='symptoms.symptomreport')),
            ],
            options={
                'verbose_name_plural': 'symptom entries',
            },
        ),
    ]
