# Generated by Django 6.0.5 on 2026-06-01 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChemotherapyCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('on_chemotherapy', models.BooleanField(default=True)),
                ('cycle_number', models.SmallIntegerField(default=1)),
                ('adverse_event', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChemotherapyRegimen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('on_chemotherapy', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('treatment_intent', models.CharField(blank=True, choices=[('curative', 'Curative'), ('palliative', 'Palliative')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
