# Generated by Django 6.0.5 on 2026-06-01 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chemotherapy', '0001_initial'),
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemotherapycycle',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemotherapy_cycles', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='chemotherapyregimen',
            name='chemotherapy_regimen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemotherapy_regimen', to='core.chemotherapyregimenname'),
        ),
        migrations.AddField(
            model_name='chemotherapyregimen',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chemotherapy_regimen', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='chemotherapycycle',
            name='chemotherapy_regimen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chemotherapy_cycles', to='chemotherapy.chemotherapyregimen'),
        ),
    ]
