# Generated by Django 6.0.5 on 2026-06-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinician',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default-clinician.jpeg', null=True, upload_to='clinician_profiles/'),
        ),
    ]
