# Generated by Django 6.0.5 on 2026-06-03 09:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0003_alter_clinician_profile_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinician',
            name='license_number',
        ),
        migrations.CreateModel(
            name='ClinicianVerifiation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospital', models.CharField(blank=True, max_length=100)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('license_expiration_date', models.DateField()),
                ('current_license', models.ImageField(upload_to='clinician_licenses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinician', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='clinician_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
