# Generated by Django 6.0.5 on 2026-06-03 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0004_remove_clinician_license_number_clinicianverifiation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClinicianVerifiation',
            new_name='ClinicianVerification',
        ),
        migrations.AddField(
            model_name='clinician',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
