# Generated by Django 6.0.5 on 2026-06-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0005_rename_clinicianverifiation_clinicianverification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinician',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=100),
            preserve_default=False,
        ),
    ]
