# Generated by Django 6.0.5 on 2026-06-05 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0006_alter_clinician_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinician',
            name='is_verified',
        ),
    ]
