# Generated by Django 6.0.5 on 2026-06-05 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0007_remove_clinician_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
