# Generated by Django 6.0.5 on 2026-06-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0008_clinician_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinician',
            name='verification_requested',
            field=models.BooleanField(default=False),
        ),
    ]
