# Generated by Django 6.0.5 on 2026-06-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0009_clinician_verification_requested'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicianverification',
            options={'ordering': ['created_at'], 'verbose_name': 'Clinician Verification'},
        ),
    ]
