# Generated by Django 6.0.5 on 2026-06-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0010_alter_clinicianverification_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinician',
            old_name='clinician',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='clinician',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='clinician',
            name='verification_requested',
        ),
    ]
