# Generated by Django 6.0.5 on 2026-06-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0011_rename_clinician_clinician_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicianverification',
            old_name='clinician',
            new_name='user',
        ),
    ]
