# Generated by Django 6.0.5 on 2026-06-01 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='patientS', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='allergy_substance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_allergies', to='core.allergysubstance'),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_allergies', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patientallergy',
            name='reaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.allergyreaction'),
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(related_name='patients', through='patients.PatientAllergy', to='core.allergysubstance'),
        ),
        migrations.AddField(
            model_name='patientcancer',
            name='cancer_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_cancers', to='core.cancertype'),
        ),
        migrations.AddField(
            model_name='patientcancer',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_cancers', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='cancer',
            field=models.ManyToManyField(related_name='patients', through='patients.PatientCancer', to='core.cancertype'),
        ),
        migrations.AlterUniqueTogether(
            name='patientallergy',
            unique_together={('patient', 'allergy_substance')},
        ),
    ]
