# Generated by Django 6.0.5 on 2026-06-02 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicians', '0003_alter_clinician_profile_picture'),
        ('core', '0001_initial'),
        ('patients', '0003_alter_patient_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='managing_consultant',
        ),
        migrations.AddField(
            model_name='patient',
            name='primary_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='clinicians.clinician'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='patients', through='patients.PatientAllergy', to='core.allergysubstance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cancer',
            field=models.ManyToManyField(blank=True, related_name='patients', through='patients.PatientCancer', to='core.cancertype'),
        ),
    ]
