# Generated by Django 6.0.5 on 2026-06-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_patient_managing_consultant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
